/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#define RCC_AHB1ENR (*(volatile uint32_t *)0x40023830)
#define GPIOA_MODER (*(volatile uint32_t *)0x40020000)
#define GPIOA_ODR (*(volatile uint32_t *)0x40020014)

#define RCC_APB1ENR (*(volatile uint32_t *)0x40023840)
#define TIM2_PSC    (*(volatile uint32_t *)0x40000028)
#define TIM2_ARR    (*(volatile uint32_t *)0x4000002C)
#define TIM2_CR1 (*(volatile uint32_t *)0x40000000)
#define TIM2_DIER (*(volatile uint32_t *)0x4000000C)
#define TIM2_SR     (*(volatile uint32_t *)0x40000010)

#define NVIC_ISER0  (*(volatile uint32_t *)0xE000E100)

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

volatile uint32_t timer_flag = 0;

void TIM2_IRQHandler(void){
	TIM2_SR &= ~(1<<0);
	timer_flag  = 1;
}
int main(void)
{
	RCC_AHB1ENR |= (1<<0);
	RCC_APB1ENR |= (1<<0);

	GPIOA_MODER &= ~(3<<10);
	GPIOA_MODER |= (1<<10);

	TIM2_PSC = 15999;
	TIM2_ARR = 499;

	TIM2_DIER |= (1<<0);
	NVIC_ISER0 |= (1<<28);

	TIM2_CR1 |= (1<<0);

    /* Loop forever */
	for(;;){
		if(timer_flag){
			GPIOA_ODR ^= (1<<5);
			timer_flag = 0;
		}
	}
}
