/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f446xx.h"
#include <stdint.h>


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	GPIOA->MODER &= ~(3U<<0);
	GPIOA->MODER |= (2U<<0);
	GPIOA->AFR[0] &= ~(15U<<0);
	GPIOA->AFR[0] |= (1U<<0);

	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
	TIM2->PSC = 15;
	TIM2->ARR = 999;
	TIM2->CCR1 = 0;

	TIM2->CCMR1 &= ~(7U<<4);
	TIM2->CCMR1 |= (6U<<4);
	TIM2->CCER |= TIM_CCER_CC1E;

	TIM2->CR1 |= TIM_CR1_ARPE;
	TIM2->CCMR1 |= TIM_CCMR1_OC1PE;

	TIM2->EGR |= TIM_EGR_UG;

	TIM2->CR1 |= TIM_CR1_CEN;

    /* Loop forever */
	for(;;){
		    for (int i=0;i<=999;i++)
		    {
		        TIM2->CCR1 = i;
		        for (volatile int j=0;j<1000;j++) {}
		    }

		    for (int i=999;i>=0;i--)
		    {
		        TIM2->CCR1 = i;
		        for (volatile int j=0;j<1000;j++) {}
		    }
	}
}
